apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: destination-kn
  labels: 
    serving.knative.dev/visibility: cluster-local
spec:
  template:
    spec:
      containers:
        - image: quay.io/zeagur/destination:latest
          env:
            - name: HOST_IP
              value: destination
            - name: SCHEME
              value: http