apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: bee-kn
spec:
  template:
    spec:
      containers:
        - image: quay.io/zeagur/bee-ui:latest
          env:
            - name: DESTINATION_URL
              value: http://destination-kn.svl-demo.svc.cluster.local